# Generated by Django 3.1.4 on 2020-12-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assignment_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
