# Generated by Django 3.1.4 on 2020-12-28 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201228_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='members',
            field=models.ManyToManyField(related_name='classroom_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
